version: "3"
services:
  db:
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password
    env_file: dados_do_banco.env
    networks:
      banco:
        aliases:
          - db
    volumes:
      - ./banco:/var/lib/mysql

  api:
    image: node
    working_dir: /home/node/app
    depends_on:
      - db
    ports:
      - "3001:3001"
    networks:
      banco:
    command: bash -c 'while !</dev/tcp/db/3306; do sleep 1; done; sleep 1; npx nodemon src/server.js'
    volumes:
      - ./api-autoatendimento:/home/node/app
    env_file: dados_da_api.env
    environment:
      - SERVER_PORT=3001

  client:
    build: ./client-docker
    env_file: dados_do_client.env
    depends_on:
      - api
    ports:
      - "3000:80"

networks:
  banco:
