version: "3"

services:
  db:
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: autoatendimento
      MYSQL_USER: ifrn
      MYSQL_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    networks:
      - autoatendimento
    volumes:
      - db_data:/var/lib/mysql


  api:
    build:
      context: ./api-autoatendimento
      dockerfile: Dockerfile
    working_dir: /src

    depends_on:
      - db
        
    ports:
      - "3001:3001"
    networks:
      - autoatendimento
    volumes:
      - ./api:/app

  client:
    build:
      context: ./autoatendimento
      dockerfile: Dockerfile
    depends_on:
      - api
    ports:
      - "3000:80"
    networks:
      - autoatendimento

networks:
  autoatendimento:
    name: autoatendimento
volumes:
  db_data: